name: Deploy to EC2

on:
  push:
    branches:
      - master  # or main, depending on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 Host to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /path/to/weather-app  # change this to the directory where your app is located
          git pull origin master   # pull the latest changes from GitHub
          # Add any additional deployment steps if necessary, e.g. installing dependencies
          # python3 -m pip install -r requirements.txt
          sudo systemctl restart weather-app.service  # Assuming you're using systemd to run the app
        EOF
