name: Deploy FastAPI to Amazon Linux EC2

on:
  push:
    branches:
      - master  # or main, based on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy app files to EC2 (excluding .git and venv)
        run: |
          rsync -avz --exclude='.git' --exclude='venv' ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/weather-app/

      - name: Deploy and run app on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Optional: kill existing app
            pkill uvicorn || true

            # Move to app directory
            cd weather-app

            # Install pip and dependencies
            sudo yum install -y python3
            python3 -m ensurepip --upgrade
            pip3 install --upgrade pip
            pip3 install -r requirements.txt

            # Run FastAPI app
            nohup uvicorn main:app --host 0.0.0.0 --port 80 > app.log 2>&1 &
          EOF
